#include "../include/AudioFile.h"
#include "../include/FIRFilter.h"
#include <chrono>

using namespace std;

int main() {
    AudioFile<float> audioFile;
    audioFile.load (ROOT_DIR + "sampleAudio.wav");
    audioFile.printSummary();

    int numSamples = audioFile.getNumSamplesPerChannel();
    float output[numSamples];
    // coefficients generated with MatLab (okay generated by ChatGPT using MatLab)
    // these are (supposedly) representing a cut-off frequency of 400Hz
    float coefficients[11] = {0.01444,0.03044,0.07242,0.12450,0.16675,0.18291,0.16675,0.12450,0.07242,0.03044,0.01444};

    auto start_time = chrono::high_resolution_clock::now();

    //convolution(audioFile.samples[0].data(), coefficients, output);
    convolution_sw(audioFile.samples[0].data(), numSamples, coefficients, 11, output);

    auto end_time = chrono::high_resolution_clock::now();

    auto elapsed_time = chrono::duration_cast<chrono::milliseconds>(end_time - start_time).count();

    std::cout << "Convolution runtime: " << elapsed_time << " ms" << std::endl;

    // if we want to hear the audio!
    // for (int i = 0; i < numSamples; i++)
    // {   
	//     audioFile.samples[0][i] = filteredSamples[i];
    // }
    // audioFile.save("audioFile.wav");

    writeData(option::output_gold, output, numSamples); // write to output.dat

    // string command = "diff -w " + ROOT_DIR + "output.dat " + ROOT_DIR + "output.gold.dat";
    //   printf ("Comparing against output data \n");
    // if (system(command.c_str())) {
  	// fprintf(stdout, "*******************************************\n");
  	// fprintf(stdout, "FAIL: Output DOES NOT match the golden output\n");
  	// fprintf(stdout, "*******************************************\n");
    //    return 1;
    // } else {
  	// fprintf(stdout, "*******************************************\n");
  	// fprintf(stdout, "PASS: The output matches the golden output!\n");
  	// fprintf(stdout, "*******************************************\n");
    //    return 0;
    // }

}
